### ISSUE TITLE
[EPIC ISSUE] Manifests Grant 403 Error

### ISSUE THREAD

**Issue by ItsJunction** [polynite/splash#2]
Manifests are shown as 403 now in splash.
![image](https://user-images.githubusercontent.com/62995181/101991015-d53edc80-3ca1-11eb-9342-214ef6f8c7b7.png)
*image via @kem0o*

Projected to have started happened around 3 days ago (however I haven't used since just before then).

According to mix we need a key (query string), rendering this tool useless for older version. However, we can download the latest patch rn at this url:

EDIT: **TOKEN IN URL SEEMS TO BE NOW INVALID**:
https://epicgames-download1.akamaized.net/Builds/Fortnite/CloudDir/pxgus3IjKexjBYe8O0qy6lPWTTBxOg.manifest?ak_token=exp=1607773399~hmac=a1aa9b0438ca9f4bd5f39ec99d8c9356f8a7834b95eb25d3fd83866d1ecbd3ce

**Comment by 3ldor** [comment]
It does indeed sadly seem like the manifests have been removed from their CDNs. I added support for downloading the latest build in c13b13bdbb1470554c149d65eda30ac8e1e04f98. You _can_ download older builds if you happen to have the full manifest, too.
