### ISSUE TITLE
Feature Request: Be able to specify files to download in like an text file

### ISSUE THREAD

**Issue by nutterthanos** [polynite/splash#5]

**Comment by 3ldor** [comment]
You can already use the `-files=...` parameter to selectively download files. Is there any use case where this is not enough?

**Comment by nutterthanos** [comment]
well it would take forever to choose the files then

**Comment by 3ldor** [comment]
The feature is intended to be used if you only want to download a few files. Why'd you want to download a lot of files, but not all?

**Comment by nutterthanos** [comment]
> The feature is intended to be used if you only want to download a few files. Why'd you want to download a lot of files, but not all?

idk
